CONNECT demo / AS SYSDBA
alter session set "_ORACLE_SCRIPT"=true;
CREATE USER LIBRARY IDENTIFIED BY "library"
DEFAULT TABLESPACE USERS;
GRANT CONNECT, RESOURCE, CREATE VIEW TO library;
CONNECT library/library

CREATE TABLE MEMBER(
MEMBER_ID NUMBER(10) NOT NULL,
LAST_NAME VARCHAR2(25) NOT NULL,
FIRST_NAME VARCHAR2(25),
ADDRESS VARCHAR2(100),
CITY VARCHAR2(30),
PHONE VARCHAR2(15),
JOIN_DATE DATE DEFAULT SYSDATE,
PRIMARY KEY (MEMBER_ID)
);



CREATE TABLE TITLE(
TITLE_ID NUMBER(10) NOT NULL,
TITLE VARCHAR2(60) NOT NULL,
DESCRIPTION VARCHAR2(400) NOT NULL,
RATING VARCHAR2(4) CHECK(RATING IN ('G', 'PG', 'R', 'NC17', 'NR')),
CATEGORY VARCHAR2(20) CHECK(CATEGORY IN ('DRAMA', 'COMEDY', 'ACTION', 'CHILD', 'SCIFI', 'DOCUMENTARY')),
RELEASE_DATE DATE,
PRIMARY KEY (TITLE_ID)
);


CREATE TABLE TITLE_COPY(
COPY_ID NUMBER(10) NOT NULL,
TITLE_ID NUMBER(10) NOT NULL,
STATUS VARCHAR2(15) CHECK(STATUS IN('AVAILABLE', 'DESTROYED', 'RENTED', 'RESERVED')),
FOREIGN KEY (TITLE_ID) REFERENCES TITLE(TITLE_ID),
PRIMARY KEY(COPY_ID, TITLE_ID)
);

CREATE TABLE RENTAL(
BOOK_DATE DATE DEFAULT SYSDATE,
MEMBER_ID NUMBER(10) NOT NULL,
COPY_ID NUMBER(10) NOT NULL,
ACT_RET_DATE DATE,
EXP_RET_DATE DATE DEFAULT SYSDATE + 2,
TITLE_ID NUMBER(10) NOT NULL,
FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER(MEMBER_ID),
FOREIGN KEY (COPY_ID,TITLE_ID) REFERENCES TITLE_COPY(COPY_ID,TITLE_ID),
PRIMARY KEY (BOOK_DATE, MEMBER_ID, COPY_ID, TITLE_ID)
);


CREATE TABLE RESERVATION(
RES_DATE DATE NOT NULL,
MEMBER_ID NUMBER(10) NOT NULL,
TITLE_ID NUMBER(10) NOT NULL,
FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER(MEMBER_ID),
FOREIGN KEY (TITLE_ID) REFERENCES TITLE(TITLE_ID),
PRIMARY KEY(RES_DATE, MEMBER_ID, TITLE_ID)
);


SELECT TABLE_NAME
FROM USER_TABLES
WHERE  TABLE_NAME IN ('MEMBER', 'TITLE', 'TITLE_COPY', 'RENTAL', 'RESERVATION');

SELECT CONSTRAINT_NAME, CONSTRAINT_TYPE, TABLE_NAME
FROM USER_CONSTRAINTS
WHERE  TABLE_NAME IN ('MEMBER', 'TITLE', 'TITLE_COPY', 'RENTAL', 'RESERVATION');


CREATE SEQUENCE
MEMBER_ID_SEQ
START WITH 101
NOCACHE;

CREATE SEQUENCE
TITLE_ID_SEQ
START WITH 92
NOCACHE;

SELECT SEQUENCE_NAME, INCREMENT_BY, LAST_NUMBER
FROM USER_SEQUENCES
WHERE SEQUENCE_NAME IN ('MEMBER_ID_SEQ', 'TITLE_ID_SEQ');