UPDATE TITLE
SET PRICE = 25
WHERE TITLE = 'Willie and Christmas Too';

UPDATE TITLE
SET PRICE = 35
WHERE TITLE = ''Alien Again';

UPDATE TITLE
SET PRICE = 35
WHERE TITLE = 'The Glob';

UPDATE TITLE
SET PRICE = 35
WHERE TITLE = 'My Day Off';

UPDATE TITLE
SET PRICE = 30
WHERE TITLE = 'Miracles on Ice';

UPDATE TITLE
SET PRICE = 35
WHERE TITLE = 'Soda Gang';

UPDATE TITLE
SET PRICE = 29
WHERE TITLE = 'Interstellar Wars';